<#-- 
  Copyright 2021 Kafdrop contributors.
  Licensed under the Apache License, Version 2.0
-->
<#import "/spring.ftl" as spring />

<!-- Bloque principal -->
<div class="pb-0 mt-5 mb-4" style="background-color:#0C1A1A; color:#ffffff; min-height:150px;">
    <div class="container">
            <!-- Texto descriptivo o créditos -->
        <p style="color:#ffffff;">
            Mas información <strong>antony.mongelopez@ucr.ac.cr</strong>
        </p>

        </div>
</div>
